OFFICIAL_OPTIONS = {
    "Deportes": [
        "Basket",
        "Volley",
        "Futbol",
        "Ajedrez",
        "Tenis de mesa",
        "Atletismo",
        "Natación",
        "Ciclismo",
        "No hago deportes",
    ],
    "Juegos": [
        "League of Legends",
        "Minecraft",
        "Valorant",
        "CS:GO 2",
        "Rocket League",
        "FIFA",
        "Juegos Retro/Arcade",
        "OSU!",
        "Terraria",
        "Sims",
    ],
    "Series": [
        "Acción",
        "Aventura",
        "Comedia",
        "Drama",
        "Romance",
        "Sci-Fi",
        "Anime",
        "Horror",
        "Thriller",
        "Documentales",
    ],
    "Pref": [
        "Quedarte en casa jugando",
        "Salir a carretear",
        "Carretear en casa",
        "Quedarte en casa viendo series/peliculas",
    ],
    "Comida": [
        "Completos",
        "Hamburguesa",
        "Sushi",
        "Pizza",
        "Asado",
        "Pastas",
        "Ramen",
        "Ensaladas",
        "Papas fritas",
        "Pasteles",
        "Sopaipillas",
        "Humitas",
        "Tacos",
        "Mariscos",
    ],
    "Musica": [
        "Pop",
        "Rock",
        "Rock Latino",
        "Reggaeton",
        "Trap",
        "Hip Hop",
        "Indie",
        "Metal",
        "J-Pop",
        "OST Anime/Videojuegos",
        "Vocaloid",
        "Electrónica",
        "R&B",
        "Grunge",
        "Urbana",
        "Techno",
        "Phonk",
        "Underground",
    ],
    "Dieta": ["Omnívora", "Vegetariana", "Vegana", "Pescetariana"],
    "Trago": [
        "Piscola",
        "Ron",
        "Cerveza",
        "Vino",
        "Vodka",
        "Mojito",
        "Gin",
        "Tequila",
        "Sin alcohol",
    ],
    "Hobby": [
        "Videojuegos",
        "Música",
        "Lectura",
        "Dibujar",
        "Pintar",
        "Fotografía",
        "Cocinar",
        "Repostería",
        "Programar",
        "Manualidades",
        "Deportes",
        "Jardinería",
        "Estudio",
        "Escritura",
        "Juegos de mesa",
    ],
    "Idiomas": [
        "Inglés",
        "Japonés",
        "Alemán",
        "Francés",
        "Coreano",
        "Portugués",
        "Italiano",
        "Chino",
        "Ruso",
        "Árabe",
        "Español",
    ],
}

ALIASES = {
    "Deportes": {
        "futbol": "Futbol",
        "football": "Futbol",
        "balompie": "Futbol",
        "voley": "Volley",
        "volley": "Volley",
        "basquet": "Basket",
        "basketball": "Basket",
        "ping pong": "Tenis de mesa",
        "tenis mesa": "Tenis de mesa",
        "natacion": "Natación",
        "bike": "Ciclismo",
        "cleta": "Ciclismo",
        "ciclismo": "Ciclismo",
        "ninguno": "No hago deportes",
        "no hago deportes": "No hago deportes",
        "no practico": "No hago deportes",
        "gym": "No hago deportes",
        "running": "Atletismo",
        "handball": "Volley",
        "ultimate fressbe": "Futbol",
        "taekwondo": "Atletismo",
        "boxeo": "Atletismo",
        "calistenia": "Atletismo",
        "gimnasio": "Atletismo",
        "pesas": "Atletismo",
        "tenis playa": "Tenis de mesa",
    },
    "Juegos": {
        "lol": "League of Legends",
        "league": "League of Legends",
        "rocket league": "Rocket League",
        "rocketleague": "Rocket League",
        "csgo": "CS:GO 2",
        "counter": "CS:GO 2",
        "rocket": "Rocket League",
        "fifa": "FIFA",
        "osu": "OSU!",
        "retro": "Juegos Retro/Arcade",
        "arcade": "Juegos Retro/Arcade",
        "mc": "Minecraft",
        "wild rift": "League of Legends",
        "tft": "League of Legends",
        "free fire": "Valorant",
        "fortnite": "Valorant",
        "doom": "CS:GO 2",
        "team fortress 2": "CS:GO 2",
        "age of empires": "Juegos Retro/Arcade",
        "forza": "Rocket League",
        "nfs": "Rocket League",
        "juegos de carreras": "Rocket League",
        "baldur’s gate 3": "Terraria",
        "baldurs gate 3": "Terraria",
        "deltarune": "Terraria",
        "the legend of zelda": "Terraria",
        "assassin's creed": "Terraria",
        "victoria 2": "Juegos Retro/Arcade",
    },
    "Series": {
        "ciencia ficcion": "Sci-Fi",
        "starwars": "Sci-Fi",
        "super heroes": "Acción",
        "crimen": "Thriller",
        "historicas": "Drama",
        "adolescentes": "Drama",
        "coreanas": "Drama",
        "terror psicologico": "Horror",
        "monos chinos": "Anime",
        "the notebook": "Romance",
        "laland": "Romance",
        "joe black": "Romance",
    },
    "Pref": {
        "jugar tenis": "Salir a carretear",
        "ir al gym": "Salir a carretear",
        "salir a caminar": "Salir a carretear",
        "o salir con amigos": "Salir a carretear",
        "excepto ver peliculas": "Carretear en casa",
    },
    "Comida": {
        "fideos": "Pastas",
        "pasta": "Pastas",
        "hamburguesas": "Hamburguesa",
        "ensalada": "Ensaladas",
        "ramen": "Ramen",
        "sushis": "Sushi",
        "sopaipillas pasadas": "Sopaipillas",
        "pastel de choclo": "Humitas",
        "lasaña": "Pastas",
    },
    "Musica": {
        "jpop": "J-Pop",
        "j-pop": "J-Pop",
        "ost": "OST Anime/Videojuegos",
        "anime ost": "OST Anime/Videojuegos",
        "vocaloid": "Vocaloid",
        "hiphop": "Hip Hop",
        "hip hop": "Hip Hop",
        "rock latino": "Rock Latino",
        "electro": "Electrónica",
        "electronica": "Electrónica",
        "r&b": "R&B",
    },
    "Dieta": {
        "omnivora": "Omnívora",
        "omnívora": "Omnívora",
        "vegetariano": "Vegetariana",
        "vegetariana": "Vegetariana",
        "vegano": "Vegana",
        "vegana": "Vegana",
        "pescetariano": "Pescetariana",
        "pescetariana": "Pescetariana",
        "como de todo": "Omnívora",
        "de todo": "Omnívora",
    },
    "Trago": {
        "agua": "Sin alcohol",
        "coca-cola": "Sin alcohol",
        "cocacola": "Sin alcohol",
        "jugo": "Sin alcohol",
        "limonada": "Sin alcohol",
        "pepsi": "Sin alcohol",
        "limonsoda": "Sin alcohol",
        "sprite": "Sin alcohol",
        "no tomo": "Sin alcohol",
        "fanta": "Sin alcohol",
        "monster": "Sin alcohol",
        "lemon stone": "Sin alcohol",
        "tropical": "Sin alcohol",
        "pisco sour": "Piscola",
        "mistral ice": "Vodka",
        "terremoto": "Vino",
        "margarita": "Tequila",
        "michelada": "Cerveza",
        "pina colada": "Ron",
    },
    "Hobby": {
        "videojuego": "Videojuegos",
        "gaming": "Videojuegos",
        "musica": "Música",
        "tocar instrumentos": "Música",
        "leer": "Lectura",
        "dibujar": "Dibujar",
        "pintar": "Pintar",
        "fotografia": "Fotografía",
        "cocinar": "Cocinar",
        "reposteria": "Repostería",
        "programar": "Programar",
        "manualidades": "Manualidades",
        "deportes": "Deportes",
        "jardineria": "Jardinería",
        "estudio": "Estudio",
        "escritura": "Escritura",
        "mtg": "Juegos de mesa",
        "juegos de mesa": "Juegos de mesa",
        "instrumentos": "Música",
        "colaborar en el preu usm": "Estudio",
        "salir a pasear": "Deportes",
        "videos": "Videojuegos",
        "estudiar": "Estudio",
    },
    "Idiomas": {
        "ingles": "Inglés",
        "japones": "Japonés",
        "aleman": "Alemán",
        "frances": "Francés",
        "coreano": "Coreano",
        "portugues": "Portugués",
        "italiano": "Italiano",
        "chino": "Chino",
        "ruso": "Ruso",
        "arabe": "Árabe",
        "peruano": "Español",
    },
}
